version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: sinatra_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  sinatra:
    image: test-sinatra
    container_name: sinatra
    ports:
      - '80:3000'
    env_file:
      - .env
